---
#
# The function of this book is to install Signal Science agent for the Web Application Firewall - WAF
# Creator Jordan Awesome Robison 
# Email: jordan.robison@wellsky.com
#
# Tunes while coding: https://www.youtube.com/watch?v=I8Z9FTRnj9I
#
# Quote: So hey you get off of my cloud
# I'm the one they sent to control this crowd
# Guaranteed to put smiles on faces
# As of my control on a regular basis
# 
# Jira Ticket: HSRE-750
# Confluence Page: Coming soon
# AFT Repo: https://github.com/mediwareinc/ATF
# Signal Science Doc page to install Windows Agent: https://docs.signalsciences.net/install-guides/agent-installation/windows-agent/
#
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Create folder for Agent.conf
      win_file:
      path: C:\Program Files\Signal Sciences\Agent
      state: directory 
      
    - name: Download the sigsci-agent # Url to the agent page: https://dl.signalsciences.net/?prefix=sigsci-agent/
      win_get_url:
        url: 'https://dl.signalsciences.net/sigsci-agent/sigsci-agent_latest.msi'
        dest: C:\devops\

    - name: Download the IIS module # Url to the IIS module page: https://dl.signalsciences.net/?prefix=sigsci-module-iis/
      win_get_url:
        url: 'https://dl.signalsciences.net/sigsci-module-iis/sigsci-module-iis_latest.msi'
        dest: C:\devops\
# Copy the agent file over 
    - name: Copy the agent.conf from git
      win_copy:
        src: agent.conf
        dest: C:\Program Files\Signal Sciences\Agent    

# Running the Install on both the Agent and the IIS module

    - name: Install Agent MSI
      win_shell: C:\devops\sigsci-agent_latest.msi
      args:
         executable: cmd
      register: msi_install_out
       
    - name: Install IIS Module
      win_shell: C:\devops\sigsci-module-iis_latest.msi
      args:
         executable: cmd
      register: iis_install_out