---
#
# The function of this book is to install Signal Science agent for the Web Application Firewall - WAF
# Creator Jordan Awesome Robison 
# Email: jordan.robison@wellsky.com
#
# Tunes while coding: https://www.youtube.com/watch?v=I8Z9FTRnj9I
#
# Quote: So hey you get off of my cloud
# I'm the one they sent to control this crowd
# Guaranteed to put smiles on faces
# As of my control on a regular basis
# 
# Jira Ticket: HSRE-750
# Confluence Page: Coming soon
# AFT Repo: https://github.com/mediwareinc/ATF
# Signal Science Doc page to install Windows Agent: https://docs.signalsciences.net/install-guides/agent-installation/windows-agent/
#
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Create folder for Agent.conf
      win_command: cmd.exe /c mkdir C:\Program Files\Signal Sciences\Agent
      state: present 

#    - name: Create folder for IIS module
#      win_command: cmd.exe /c mkdir C:\\Program Files\\Signal Sciences\\IIS Module
#      state: present
      
    - name: Download the sigsci-agent # Url to the agent page: https://dl.signalsciences.net/?prefix=sigsci-agent/
      win_get_url:
        url: 'https://dl.signalsciences.net/sigsci-agent/sigsci-agent_latest.msi'
        dest: C:\Program Files\Signal Sciences\Agent

    - name: Download the IIS module # Url to the IIS module page: https://dl.signalsciences.net/?prefix=sigsci-module-iis/
      win_get_url:
        url: 'https://dl.signalsciences.net/sigsci-module-iis/sigsci-module-iis_latest.msi'
        dest: C:\Program Files\Signal Sciences\IIS Module
# Copy the agent file over 
    - name: Copy the agent.conf from git
      win_copy:
        src: agent.conf
        dest: C:\Program Files\Signal Sciences\Agent
        state: present

    - name: Copy the agent.conf from git
      win_copy:
        src: sigsci-agent_latest.msi
        dest: C:\Program Files\Signal Sciences\Agent\
        state: present

    - name: Copy the agent.conf from git
      win_copy:
        src: sigsci-module-iis_latest.msi
        dest: C:\Program Files\Signal Sciences\IIS Module
        state: present
    
    - name: Install MSI
      win_msi: 
        path: C:\Program Files\Signal Sciences\IIS Module
        state: present

    
#   
# Alternatively, for unattended installation, use the following command. This command will not display any output, but will install into %PROGRAMFILES%\Signal Sciences\IIS Module by default. 
# It will also register the Signal Sciences module and configuration with IIS.
# msiexec /qn /i sigsci-module-iis_latest.msi
#
    - name: Run IIS module install
      win_shell: msiexec /qn /i sigsci-module-iis_latest.msi

    - name: Results of IIS
      win_command: msiexec /qn /i sigsci-module-iis_latest.msi
      register: sigsci_iis
      
# To confirm that the module DLL has been registered with IIS, run the following from a terminal running as Administrator to verify the SignalSciences module is listed:
#
# "%PROGRAMFILES%\Signal Sciences\IIS Module\SigsciCtl.exe" Get-Modules
#
    - name: To confirm that the module DLL has been registered with IIS
      win_command: C:\Program Files\Signal Sciences\IIS Module\SigsciCtl.exe Get-Modules

# To confirm that the module configuration has been registered, run the following from a terminal running as Administrator to output the current configuration.
#
# "%PROGRAMFILES%\Signal Sciences\IIS Module\SigsciCtl.exe" Get-Configs

    - name: To confirm that the module configuration has been registered
      win_command: C:\Program Files\Signal Sciences\IIS Module\SigsciCtl.exe Get-Configs





